apiVersion: v1
kind: Pod
metadata:
  name: cm-env
  labels:
    name: cm-env
spec:
  containers:
  - name: nginx
    image: k8spracticalguide/nginx:1.15.5
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    env:
    - name: DATABASE_HOST
      valueFrom:
        configMapKeyRef:
          name: my-cm
          key: DATABASE_HOST
