apiVersion: v1
kind: Pod
metadata:
  name: cm-volume
  labels:
    name: cm-volume
spec:
  containers:
  - name: nginx
    image: k8spracticalguide/nginx:1.15.5
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    volumeMounts:
      - name: my-cm
        readOnly: true
        mountPath: /var/nginx
  volumes:
  - name: my-cm
    configMap:
      name: my-cm
      items:
      - key: nginx.conf
        path: nginx.conf
